### ISSUE TITLE
motivation for dockerfiles

### ISSUE THREAD

**Issue by ttimbers** [ropenscilabs/r-docker-tutorial#11]
In lesson #5 we layout the motivation for dockerfiles to be that we'd like to add more things to our container, like R packages and data that will be pre-installed and ready to go as soon as we start up. I am not sure that this is really why you would want to make a docker file. I think a docker file is important for reproducibility & security. 

You can take a docker image and add data and r-packages interactively, and then commit that version of the container to update or make a new image. But what an image alone doesn't give you is the information about what is inside that container. The dockerfile is where you get all that info. So essentially it is an install recipe for the environment you need to run your code and, from a security aspect a dockerfile tells you whether or not there would be any malicious code in the image it would build (a real worry for HPC, Compute Canada for example, which is why they won't let you use docker with root access on their systems).

@BillMills, thoughts?

**Comment by cboettig** [comment]
I agree that the Dockerfile is a big win for reproducibility in that it provides both a compact, human-readable (well, more readable than a binary image; but not necessarily all that readable) and machine-readable recipe of the computational environment.  

I do think it is important not to oversell the Dockerfile in this way though -- how precisely a Dockerfile will continue to reproduce the same environment depends both on:
1.  How the author writes the Dockerfile in the first place -- for instance, do you lock all the versions of packages you install (with tricks like the MRAN mirror etc) or just install whatever is 'current'?  
2. External factors that can still change, such as low-level system dependencies.  In general Linux distributions are designed so that even older versions of software can be patched to address things like major security flaws (e.g. I have early Docker images still susceptible to heartbleed and shell-shock if they aren't rebuilt).  Clearly there's a trade-off between reproduciblity and security here (one person's bug might be another person's feature...).  And a given distribution is only supported in this way for a finite window of time. 

My only point being with (2) that even if you do (1) carefully, Dockerfiles aren't designed to create bitwise identical versions of images each time, and generally this is for good reason.  Preserving the whole Docker image itself is (modulo differences external to docker: kernel, hardware, etc) a bitwise identical copy of the environment, but an opaque one.

**Comment by katieannemills** [comment]
Sorry for the slow reply, been traveling~

Anyway - you're both right. The core value of the Dockerfile isn't in what it _does_ but what it _says you did_; it is, first and foremost, a piece of documentation rather than a functional tool. The reason I like them so much and push learners to use them, is that if the Dockerfile is how you craft your image, then you a priori have a perfect record of how you built your container. @cboettig is certainly correct that this may diverge over time - but I think in general this is a much slower rot than manually composed documentation that falls out of step essentially instantly.

**Comment by katieannemills** [comment]
addressed in #28
