### ISSUE TITLE
Overlap lessons 3 and 4

### ISSUE THREAD

**Issue by HeidiSeibold** [ropenscilabs/r-docker-tutorial#6]
We already show how to commit in lesson 3 and then lesson 4 is supposed to introduce commiting:

We have the following options
- Show it twice (3+4), then we have to make sure there is at least some new info in 4
- Not show it in 3, which makes it difficult with the closing of the terminal with exit
- Delete lesson 4, which makes commiting seem less important than it is

What do you think?

**Comment by katieannemills** [comment]
It depends on the workflow we want to encourage students to use (and we should pick _one_ workflow, to keep things simple for beginners). Personally, I never actually use `commit`, because I want my docker container to be exactly described by my Dockerfile - committing changes to the container without articulating them in the Dockerfile will invariably cause the container and its docs to get out of step.

Ergo, delete lesson 4.

**Comment by HeidiSeibold** [comment]
Ok, I did that.

Thanks for your input!
